language: node_js
node_js:
  - "14"
  - "16"
before_install:
  - npm install -g npm-install-peers
  - npm-install-peers
script:
  - npm test
  - npm run build
after_success:
  - bash <(curl -s https://codecov.io/bash)
